version: '3'

services:
  hub:
    image: selenium/hub:latest
    expose:
      - 4444
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome-debug:latest
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5900:5900
    depends_on:
      - hub
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox-debug:latest
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5901:5900
    depends_on:
      - hub
    networks:
      - selenium-grid

  test-gc:
    image: oweng/rfdocker
    command: -v BROWSER:gc --outputdir /out /tests
    volumes:
      - ./tests/web:/tests:ro
      - ./results/gc:/out:rw
    depends_on:
      - demoapp
      - chrome
    networks:
      - selenium-grid

  test-ff:
    image: robotframework:latest
    command: -v BROWSER:ff --outputdir /out /tests
    volumes:
      - ./tests/web:/tests:ro
      - ./results/ff:/out:rw
    depends_on:
      - demoapp
      - firefox
    networks:
      - selenium-grid

  test-robot:
    image: robotframework:latest
    command: --outputdir /out /tests
    volumes:
      - ./tests:/tests:ro
      - ./results:/out:rw
    networks:
      - selenium-grid
networks:
  selenium-grid:
